version: "3.9"
services:
  mini-project-app-backend:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name:  mini-project-app-backend
    volumes:
      - ./app/node_modules
      - ./backend:/app
    ports:
      - 5000:5000
    depends_on:
      - mongodb
    environment:
      NODE_ENV: ${NODE_ENV}
      MONGO_URI: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb
    networks:
      - mini-project-app
  mongodb:
    image: mongo
    restart: always
    ports: 
       - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
     - mongodb-data:/data/db
    networks:
     - mini-project-app
   # mongo-express should only be used privately for development purposes.
   # It helps us interact with a mongoDB database using our browser
  mongo-express:
      image: mongo-express
      depends_on:
         - mongodb
      ports:
         - 8081:8081
      environment:
         ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
         ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
         ME_CONFIG_MONGODB_SERVER: mongodb
         ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USERNAME}
         ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
      volumes:
         - mongodb-data
      networks:
         - mini-project-app
  mini-project-app-frontend:
      restart: always
      build:
         context: ./frontend
         dockerfile: Dockerfile.dev
      container_name: mini-project-app-frontend
      volumes:
         - ./app/node_modules
         - ./frontend:/app
      ports:
         - 3000:3000
      depends_on:
         - mini-project-app-backend
      networks:
         - mini-project-app
  nginx:
      restart: always
      depends_on:
         - mini-project-app-backend
         - mini-project-app-frontend
      build:
         context: ./nginx
         dockerfile: Dockerfile.dev
      ports:
         - 8080:80
      networks:
         - mini-project-app

networks:
   mini-project-app:
      driver: bridge

volumes:
   mongodb-data:
      driver: local   