export const USER_LIST_FAIL = "USER_LIST_FAIL";
export const USER_LIST_REQUEST = "USER_LIST_REQUEST";
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";

export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";
export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";

export const USER_CREATE_REQUEST = "USER_CREATE_REQUEST";
export const USER_CREATE_SUCCESS = "USER_CREATE_SUCCESS";
export const USER_CREATE_FAIL = "USER_CREATE_FAIL";
export const USER_CREATE_RESET = "USER_CREATE_RESET";

export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
export const USER_DELETE_FAIL = "USER_DELETE_FAIL";

//photos
export const PHOTO_LIST_FAIL = "PHOTO_LIST_FAIL";
export const PHOTO_LIST_REQUEST = "PHOTO_LIST_REQUEST";
export const PHOTO_LIST_SUCCESS = "PHOTO_LIST_SUCCESS";

export const PHOTO_DELETE_REQUEST = "PHOTO_DELETE_REQUEST";
export const PHOTO_DELETE_SUCCESS = "PHOTO_DELETE_SUCCESS";
export const PHOTO_DELETE_FAIL = "PHOTO_DELETE_FAIL"

export const PHOTO_DETAILS_FAIL = "PHOTO_DETAILS_FAIL";
export const PHOTO_DETAILS_REQUEST = "PHOTO_DETAILS_REQUEST";
export const PHOTO_DETAILS_SUCCESS = "PHOTO_DETAILS_SUCCESS";


export const PHOTO_UPDATE_FAIL = "PHOTO_UPDATE_FAIL";
export const PHOTO_UPDATE_REQUEST = "PHOTO_UPDATE_REQUEST";
export const PHOTO_UPDATE_SUCCESS = "PHOTO_UPDATE_SUCCESS";